codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: nearest
  range: "40...100"
  ignore:
  - Tests/*

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches:
  - master
  - development
  behavior: default
